def main(x):
    match x[4]:
        case "MASK":
            match x[2]:
                case "IDRIS":
                    match x[0]:
                        case "SVG":
                            match x[3]:
                                case 1975:
                                    return 0
                                case 1980:
                                    return 1
                        case "BRO":
                            match x[1]:
                                case "SLASH":
                                    return 2
                                case "NIT":
                                    return 3
                case "IOKE":
                    match x[0]:
                        case "SVG":
                            return 4
                        case "BRO":
                            return 5
                case "RDOC":
                    return 6
        case "AGDA":
            match x[0]:
                case "SVG":
                    match x[3]:
                        case 1975:
                            return 7
                        case 1980:
                            return 8
                case "BRO":
                    return 9
        case "CMAKE":
            return 10
